import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Database, FolderOpen, HardDrive, Map, RefreshCw, ShieldCheck, Satellite, Trash2, Mountain } from 'lucide-react';
import { useAppContext } from '../context/AppContext';

type GISInfo = { mapsRoot: string; demRoot: string; satelliteAvailable: boolean; terrainAvailable: boolean; satellite: { name: string; sizeBytes: number; modified: string } | null; terrain: { name: string; sizeBytes: number; modified: string } | null; demTileCount: number; demTiles: string[]; demResolution: string | null };
declare global { interface Window { rnmsOffline?: any } }
const emptyInfo: GISInfo = { mapsRoot: '', demRoot: '', satelliteAvailable: false, terrainAvailable: false, satellite: null, terrain: null, demTileCount: 0, demTiles: [], demResolution: null };
const fmt = (bytes?: number) => bytes == null ? '—' : bytes < 1024 ** 3 ? `${(bytes / 1024 ** 2).toFixed(1)} MB` : `${(bytes / 1024 ** 3).toFixed(2)} GB`;

export function OfflineMapManager() {
  const { theme } = useAppContext();
  const [info, setInfo] = useState<GISInfo>(emptyInfo); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [validation, setValidation] = useState<{ valid: boolean; warnings: string[] } | null>(null);
  const refresh = useCallback(async () => { const result = await window.rnmsOffline?.getMapInfo?.(); if (result) setInfo(result); }, []);
  useEffect(() => { refresh(); }, [refresh]);
  const installMaps = async () => { setBusy(true); setMessage('Select one or more PMTiles archives…'); try { const files = await window.rnmsOffline?.selectMapFiles?.(); if (!files?.length) { setMessage('No PMTiles file selected.'); return; } const result = await window.rnmsOffline.installMapFiles(files); setMessage(`Installed ${result.installed.length} map archive(s). Unrecognized files: ${result.skipped.length}.`); setInfo(result.info); } finally { setBusy(false); } };
  const installDem = async () => { setBusy(true); setMessage('Select the folder containing genuine SRTM/HGT files…'); try { const folder = await window.rnmsOffline?.selectDemFolder?.(); if (!folder) { setMessage('No DEM folder selected.'); return; } const result = await window.rnmsOffline.installDemFolder(folder); setMessage(`Imported ${result.installed} HGT tile(s); skipped ${result.skipped}.`); setInfo(result.info); } finally { setBusy(false); } };
  const validate = async () => { setBusy(true); try { const result = await window.rnmsOffline?.validateAssets?.(); setValidation(result ?? { valid: false, warnings: ['Electron GIS bridge unavailable.'] }); await refresh(); } finally { setBusy(false); } };
  const remove = async (name: string) => { if (!confirm(`Remove ${name} from the offline GIS data store?`)) return; setBusy(true); try { await window.rnmsOffline?.removeMapAsset?.(name); setMessage(`${name} removed.`); await refresh(); } finally { setBusy(false); } };
  const Status = ({ ok, label, detail }: { ok: boolean; label: string; detail: string }) => <div className={`rounded-xl border p-4 ${ok ? 'border-emerald-200 bg-emerald-50 dark:border-emerald-900/60 dark:bg-emerald-950/20' : 'border-rose-200 bg-rose-50 dark:border-rose-900/60 dark:bg-rose-950/20'}`}><div className="flex items-center gap-2">{ok ? <CheckCircle2 className="w-5 h-5 text-emerald-600" /> : <AlertTriangle className="w-5 h-5 text-rose-600" />}<b>{label}</b></div><div className="text-xs mt-2 opacity-75">{detail}</div></div>;
  return <div className={`p-4 md:p-6 space-y-5 h-full overflow-y-auto ${theme === 'light' ? 'text-slate-800' : 'text-slate-100'}`}>
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 border-b border-slate-200 dark:border-slate-800 pb-4"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-blue-600 text-white flex items-center justify-center"><Map className="w-6 h-6" /></div><div><h2 className="text-xl font-bold">Pakistan Satellite + DEM Data Manager</h2><p className="text-xs text-slate-500">Real local PMTiles imagery and real SRTM/HGT elevation — no simulated geographic data.</p></div></div><button disabled={busy} onClick={refresh} className="px-3 py-2 rounded-lg border bg-white dark:bg-slate-900 text-xs font-bold"><RefreshCw className="inline w-4 h-4 mr-1" />Scan Data</button></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Status ok={info.satelliteAvailable} label="Satellite Imagery" detail={info.satellite ? `${fmt(info.satellite.sizeBytes)} · ${info.satellite.name}` : 'pakistan-satellite.pmtiles not installed'} /><Status ok={info.terrainAvailable} label="Terrain PMTiles" detail={info.terrain ? `${fmt(info.terrain.sizeBytes)} · ${info.terrain.name}` : 'pakistan-terrain.pmtiles not installed'} /><Status ok={info.demTileCount > 0} label="Real DEM / SRTM" detail={info.demTileCount ? `${info.demTileCount} tile(s) · ${info.demResolution}` : 'No HGT elevation tiles installed'} /></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
      <section className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 space-y-4"><h3 className="font-bold flex items-center gap-2"><Satellite className="w-5 h-5 text-blue-600" />Satellite / Terrain Archives</h3><p className="text-xs text-slate-500">Import prepared PMTiles archives. Files containing <b>satellite</b>/<b>imagery</b> become the satellite archive; files containing <b>terrain</b> become the terrain archive.</p><button disabled={busy} onClick={installMaps} className="w-full py-3 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold"><FolderOpen className="inline w-4 h-4 mr-2" />Install PMTiles</button><div className="space-y-2 text-xs">{info.satellite && <div className="flex justify-between gap-2 p-2 rounded bg-slate-50 dark:bg-slate-800"><span><b>Satellite:</b> {fmt(info.satellite.sizeBytes)}</span><button onClick={() => remove('pakistan-satellite.pmtiles')} className="text-rose-600"><Trash2 className="w-4 h-4" /></button></div>}{info.terrain && <div className="flex justify-between gap-2 p-2 rounded bg-slate-50 dark:bg-slate-800"><span><b>Terrain:</b> {fmt(info.terrain.sizeBytes)}</span><button onClick={() => remove('pakistan-terrain.pmtiles')} className="text-rose-600"><Trash2 className="w-4 h-4" /></button></div>}</div></section>
      <section className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 space-y-4"><h3 className="font-bold flex items-center gap-2"><Mountain className="w-5 h-5 text-emerald-600" />SRTM / HGT Elevation</h3><p className="text-xs text-slate-500">Select a folder containing genuine one-degree HGT tiles. The application validates 1201×1201, 3601×3601, and 7201×7201 sample formats before LOS use.</p><button disabled={busy} onClick={installDem} className="w-full py-3 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white font-bold"><FolderOpen className="inline w-4 h-4 mr-2" />Import HGT Folder</button><div className="rounded-lg bg-slate-50 dark:bg-slate-800 p-3 text-xs"><b>Installed:</b> {info.demTileCount} · <b>Resolution:</b> {info.demResolution || '—'}<br/><b>DEM folder:</b> <span className="font-mono break-all">{info.demRoot || '—'}</span></div></section>
    </div>
    <section className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 space-y-4"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h3 className="font-bold flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-amber-600" />GIS Integrity Check</h3><p className="text-xs text-slate-500">Checks that installed archives exist and HGT files have recognized dimensions.</p></div><button disabled={busy} onClick={validate} className="px-4 py-2 rounded-lg bg-slate-800 text-white text-xs font-bold"><Database className="inline w-4 h-4 mr-1" />Validate Installed Data</button></div>{validation && <div className={`rounded-lg p-3 text-xs ${validation.valid ? 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-300' : 'bg-amber-50 text-amber-800 dark:bg-amber-950/30 dark:text-amber-300'}`}><b>{validation.valid ? 'Validation passed.' : 'Validation warnings:'}</b>{validation.warnings.length ? <ul className="list-disc ml-5 mt-1">{validation.warnings.map((w, i) => <li key={i}>{w}</li>)}</ul> : ' No integrity warnings detected.'}</div>}{message && <div className="text-xs rounded-lg border border-blue-200 bg-blue-50 dark:bg-blue-950/20 p-3">{message}</div>}</section>
    <section className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5"><h3 className="font-bold flex items-center gap-2 mb-3"><HardDrive className="w-5 h-5 text-slate-500" />Deployment layout</h3><pre className="text-xs font-mono overflow-x-auto bg-slate-950 text-slate-200 rounded-lg p-4">{`RNMS/\n├── RNMS.exe\n└── rnms-data/\n    ├── maps/\n    │   ├── pakistan-satellite.pmtiles\n    │   └── pakistan-terrain.pmtiles\n    └── dem/\n        ├── NxxEyyy.hgt\n        └── ...`}</pre><p className="text-xs text-slate-500 mt-3">The data folder remains external to the executable, so large GIS datasets can be replaced or expanded without rebuilding Alpha.</p></section>
  </div>;
}
