import React from 'react';
import { useAppContext } from '../context/AppContext';
import { downloadStringAsFile } from '../lib/utils';
import { FileText, Download, FileJson, Table, Database } from 'lucide-react';

export function Reports() {
  const { sites, links, equipmentDB } = useAppContext();

  const exportJSON = () => {
    const data = { sites, links, equipmentDB };
    downloadStringAsFile(JSON.stringify(data, null, 2), 'rf-project-backup.json', 'application/json');
  };

  const exportSitesCSV = () => {
    const header = 'ID,Name,Latitude,Longitude,Elevation(m),Type\n';
    const rows = sites.map(s => `${s.id},"${s.name}",${s.lat},${s.lng},${s.elevation},${s.type}`).join('\n');
    downloadStringAsFile(header + rows, 'sites-register.csv', 'text/csv');
  };

  const exportLinksCSV = () => {
    const header = 'ID,Source Site,Target Site,Distance(km),Frequency(MHz),TX Power(dBm),Fade Margin(dB)\n';
    const rows = links.map(l => {
      const src = sites.find(s => s.id === l.sourceSiteId)?.name || l.sourceSiteId;
      const tgt = sites.find(s => s.id === l.targetSiteId)?.name || l.targetSiteId;
      return `${l.id},"${src}","${tgt}",${l.distanceKm},${l.frequencyMHz},${l.txPowerDBm},${l.fadeMarginDB}`;
    }).join('\n');
    downloadStringAsFile(header + rows, 'rf-links.csv', 'text/csv');
  };

  const exportSummary = () => {
    const content = `====================================================
RF NETWORK PLANNING EXECUTIVE SUMMARY
====================================================
Date Generated: ${new Date().toLocaleString()}
Project: Region-7 VHF Expansion

OVERVIEW:
----------------------------------------------------
Total Sites: ${sites.length}
Total RF Links: ${links.length}

SITES REGISTER:
----------------------------------------------------
${sites.map(s => `[${s.type.toUpperCase()}] ${s.name}\n  Location: ${s.lat}, ${s.lng}\n  Elevation: ${s.elevation}m`).join('\n\n')}

ACTIVE LINK BUDGETS:
----------------------------------------------------
${links.map(l => {
  const src = sites.find(s => s.id === l.sourceSiteId)?.name || 'Unknown';
  const tgt = sites.find(s => s.id === l.targetSiteId)?.name || 'Unknown';
  return `${src} <---> ${tgt}\n  Distance: ${l.distanceKm} km\n  Frequency: ${l.frequencyMHz} MHz\n  Target Fade Margin: ${l.fadeMarginDB} dB`;
}).join('\n\n')}

====================================================
Generated by RF Nexus Pro
====================================================`;
    downloadStringAsFile(content, 'executive-summary.txt', 'text/plain');
  };

  return (
    <div className="p-6 h-full flex flex-col">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-xl font-bold text-slate-800 flex items-center">
          <FileText className="w-6 h-6 mr-3 text-blue-600" />
          Reports & Export
        </h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Executive Summary Card */}
        <div className="bg-white border border-slate-300 shadow-sm rounded-xl p-6 flex flex-col">
          <div className="flex items-center mb-4">
            <div className="p-2 bg-blue-50 text-blue-600 rounded-lg mr-4 border border-blue-100">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-widest">Executive Summary</h3>
              <p className="text-xs text-slate-500 font-medium mt-1">Plain text overview of the network topology.</p>
            </div>
          </div>
          <button 
            onClick={exportSummary}
            className="mt-auto w-full flex items-center justify-center px-4 py-2 bg-slate-50 hover:bg-slate-100 text-slate-700 text-xs font-bold uppercase tracking-widest rounded border border-slate-200 transition shadow-sm"
          >
            <Download className="w-4 h-4 mr-2" />
            Download TXT
          </button>
        </div>

        {/* JSON Backup Card */}
        <div className="bg-white border border-slate-300 shadow-sm rounded-xl p-6 flex flex-col">
          <div className="flex items-center mb-4">
            <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg mr-4 border border-emerald-100">
              <FileJson className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-widest">Project Backup</h3>
              <p className="text-xs text-slate-500 font-medium mt-1">Full database export including all sites, links, and equipment.</p>
            </div>
          </div>
          <button 
            onClick={exportJSON}
            className="mt-auto w-full flex items-center justify-center px-4 py-2 bg-slate-50 hover:bg-slate-100 text-slate-700 text-xs font-bold uppercase tracking-widest rounded border border-slate-200 transition shadow-sm"
          >
            <Download className="w-4 h-4 mr-2" />
            Download JSON
          </button>
        </div>

        {/* Sites CSV Card */}
        <div className="bg-white border border-slate-300 shadow-sm rounded-xl p-6 flex flex-col">
          <div className="flex items-center mb-4">
            <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg mr-4 border border-indigo-100">
              <Table className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-widest">Sites Register</h3>
              <p className="text-xs text-slate-500 font-medium mt-1">Spreadsheet of all nodes, coordinates, and elevations.</p>
            </div>
          </div>
          <button 
            onClick={exportSitesCSV}
            className="mt-auto w-full flex items-center justify-center px-4 py-2 bg-slate-50 hover:bg-slate-100 text-slate-700 text-xs font-bold uppercase tracking-widest rounded border border-slate-200 transition shadow-sm"
          >
            <Download className="w-4 h-4 mr-2" />
            Download CSV
          </button>
        </div>

        {/* Links CSV Card */}
        <div className="bg-white border border-slate-300 shadow-sm rounded-xl p-6 flex flex-col">
          <div className="flex items-center mb-4">
            <div className="p-2 bg-amber-50 text-amber-600 rounded-lg mr-4 border border-amber-100">
              <Table className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-widest">RF Links Database</h3>
              <p className="text-xs text-slate-500 font-medium mt-1">Spreadsheet of link budgets, frequencies, and path metrics.</p>
            </div>
          </div>
          <button 
            onClick={exportLinksCSV}
            className="mt-auto w-full flex items-center justify-center px-4 py-2 bg-slate-50 hover:bg-slate-100 text-slate-700 text-xs font-bold uppercase tracking-widest rounded border border-slate-200 transition shadow-sm"
          >
            <Download className="w-4 h-4 mr-2" />
            Download CSV
          </button>
        </div>

      </div>
    </div>
  );
}
